name: (R) Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: Git tag to create. (sample 1.0.0)"
        required: true
        type: string
jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release -p:Version=${{ inputs.tag }}

    - name: Pack
      run: dotnet pack -c Release --no-build -p:Version=${{ inputs.tag }} -o ./publish

    - name: Push to NuGet
      run: dotnet nuget push "./publish/*.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create Tag
      run: |
        git tag ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}
    - name: Create release
      run: gh release create ${{ inputs.tag }} --draft --verify-tag --title "${{ inputs.tag }}" --generate-notes
